apiVersion: v1
kind: Secret
metadata:
  name: {{ include "srt2web.fullname" . }}
  labels:
    {{- include "srt2web.labels" . | nindent 4 }}
type: Opaque
data:
  auth_token: {{ .Values.secrets.auth_token | b64enc | quote }}
  jwt_secret: {{ .Values.secrets.jwt_secret | default (randAlphaNum 32) | b64enc | quote }}
