apiVersion: v1
kind: Service
metadata:
  name: {{ include "srt2web.fullname" . }}
  labels:
    {{- include "srt2web.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.srt.port }}
      targetPort: {{ .Values.srt.port }}
      protocol: UDP
      name: srt
      {{- if .Values.srt.nodePort }}
      nodePort: {{ .Values.srt.nodePort }}
      {{- end }}
  selector:
    {{- include "srt2web.selectorLabels" . | nindent 4 }}
