"""Helper to generate the complete test_harness.py file."""

from pathlib import Path

lines = []


def L(s=""):
    lines.append(s)


# ── Header ──
L('"""Tests for the harness feature tracking system (models, DB, CLI, web, parser)."""')
L("from __future__ import annotations")
L("import io, json, os, sqlite3, sys, tempfile")
L("from pathlib import Path")
L("from unittest.mock import patch, MagicMock")
L("import pytest")
L("PROJECT_ROOT = Path(__file__).parent.parent.parent")
L("sys.path.insert(0, str(PROJECT_ROOT))")
L("from harness.db import HarnessDB")
L("from harness.models import Feature, Session, AuditEntry, Progress, RiskAssessment, normalize_id")
L("from harness.migrate import migrate")
L()

# ── Fixtures ──
L("@pytest.fixture")
L("def tmp_db() -> HarnessDB:")
L('    fd, path = tempfile.mkstemp(suffix=".db")')
L("    os.close(fd)")
L("    db = HarnessDB(path)")
L("    db.connect()")
L("    yield db")
L("    db.close()")
L("    try:")
L("        os.unlink(path)")
L("    except OSError:")
L("        pass")
L()
L("@pytest.fixture")
L("def sample_feature() -> Feature:")
L("    return Feature(")
L('        id="101",')
L('        name="test_feature",')
L('        title="Test Feature",')
L('        status="pending",')
L('        area="core",')
L('        priority="Alta",')
L('        description="A test feature",')
L('        problems_identified=["Bug in module X"],')
L('        acceptance=["Test passes"],')
L('        files_to_touch=["src/file.py"],')
L('        risk_assessment=RiskAssessment(risk_level="Baja", mitigation=["Test coverage"]),')
L('        dependencies=["100"],')
L('        phase="phase1",')
L("    )")
L()
L("@pytest.fixture")
L("def seeded_db(tmp_db: HarnessDB, sample_feature: Feature) -> HarnessDB:")
L('    tmp_db.upsert_feature(sample_feature, agent="test")')
L("    return tmp_db")
L()
L()
# ── TestNormalizeID ──
L("class TestNormalizeID:")
L('    def test_strips_f_prefix(self) -> None: assert normalize_id("F115") == "115"')
L('    def test_strips_lowercase_f(self) -> None: assert normalize_id("f115") == "115"')
L('    def test_passes_through_numeric(self) -> None: assert normalize_id("115") == "115"')
L('    def test_handles_int_input(self) -> None: assert normalize_id(115) == "115"')
L('    def test_handles_none(self) -> None: assert normalize_id(None) == ""')
L('    def test_strips_whitespace(self) -> None: assert normalize_id("  F115  ") == "115"')
L()
# ── TestFeatureModel ──
L("class TestFeatureModel:")
L("    def test_auto_normalizes_id(self) -> None:")
L('        f = Feature(id="F115", name="x", title="x"); assert f.id == "115"')
L("    def test_auto_normalizes_numeric_id(self) -> None:")
L('        f = Feature(id=115, name="x", title="x"); assert f.id == "115"')
L("    def test_numeric_id_property(self) -> None:")
L('        f = Feature(id="F115", name="x", title="x"); assert f.numeric_id == 115')
L("    def test_is_done(self) -> None:")
L('        f = Feature(id="1", name="x", title="x", status="done"); assert f.is_done')
L("    def test_is_pending(self) -> None:")
L('        f = Feature(id="1", name="x", title="x", status="pending"); assert f.is_pending')
L("    def test_is_blocked(self) -> None:")
L('        f = Feature(id="1", name="x", title="x", status="blocked"); assert f.is_blocked')
L("    def test_is_in_progress(self) -> None:")
L('        f = Feature(id="1", name="x", title="x", status="in_progress")')
L("        assert f.is_in_progress; assert not f.is_done")
L("    def test_to_dict_includes_risk(self) -> None:")
L('        f = Feature(id="1", name="x", title="x", risk_assessment=RiskAssessment(risk_level="Alta"))')
L('        assert f.to_dict()["risk_assessment"]["risk_level"] == "Alta"')
L("    def test_to_dict_none_risk(self) -> None:")
L('        f = Feature(id="1", name="x", title="x")')
L('        assert f.to_dict()["risk_assessment"] is None')
L("    def test_from_json_dict_normalizes_id(self) -> None:")
L('        f = Feature.from_json_dict({"id": "F115", "name": "x", "title": "x"})')
L('        assert f.id == "115"')
L("    def test_from_json_dict_handles_legacy_fields(self) -> None:")
L(
    '        raw = {"id": "99", "name": "legacy", "title": "Legacy Feature", "status": "done", "completed_at": "2026-01-01", "session": "2026-01-01", "fix": "Fixed the bug", "summary": "All done"}'
)
L("        f = Feature.from_json_dict(raw)")
L('        assert f.status == "done"; assert f.completed_date == "2026-01-01"')
L('        assert f.started_in_session == "2026-01-01"')
L('        assert f.fix == ["Fixed the bug"]; assert f.completion_notes == "All done"')
L("    def test_from_row_parses_risk(self, seeded_db: HarnessDB) -> None:")
L('        f = seeded_db.get_feature("101"); assert f is not None')
L('        assert f.risk_assessment is not None; assert f.risk_assessment.risk_level == "Baja"')

L("    def test_from_row_parses_empty_risk(self, tmp_db: HarnessDB) -> None:")
L("        from harness.db import _now; now = _now()")
L("        conn = tmp_db.connect()")
L(
    '        conn.execute("INSERT INTO features (id, name, title, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)", ("99", "no_risk", "No Risk", "pending", now, now))'
)
L("        conn.commit()")
L('        f = tmp_db.get_feature("99")')
L("        assert f is not None; assert f.risk_assessment is None")
L("    def test_numeric_id_fallback(self) -> None:")
L('        f = Feature(id="abc", name="x", title="x"); assert f.numeric_id == 0')

# ── TestRiskAssessment ──
L()
L("class TestRiskAssessment:")
L("    def test_to_json(self) -> None:")
L('        r = RiskAssessment(risk_level="Alta", mitigation=["Code review"])')
L('        assert json.loads(r.to_json()) == {"risk_level": "Alta", "mitigation": ["Code review"]}')
L("    def test_from_json(self) -> None:")
L('        r = RiskAssessment.from_json(\'{"risk_level": "Media", "mitigation": ["Test"]}\')')
L('        assert r is not None; assert r.risk_level == "Media"')
L("    def test_from_json_none(self) -> None: assert RiskAssessment.from_json(None) is None")
L('    def test_from_json_invalid(self) -> None: assert RiskAssessment.from_json("not json") is None')
L("    def test_from_dict(self) -> None:")
L('        r = RiskAssessment.from_dict({"risk_level": "Baja", "mitigation": ["Check"]})')
L('        assert r is not None; assert r.risk_level == "Baja"')
L("    def test_from_dict_none(self) -> None: assert RiskAssessment.from_dict(None) is None")
L("    def test_defaults(self) -> None:")
L('        r = RiskAssessment(); assert r.risk_level == "Baja"; assert r.mitigation == []')
L('    def test_from_json_empty_string(self) -> None: assert RiskAssessment.from_json("") is None')

Path("tests/unit/test_harness.py").write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {len(lines)} lines")
